### PR TITLE
Added data-sharing methods and examples

### PR DESCRIPTION
**Pull request by cansik**
First of all thank you very much for creating SpoutGL, it is great to work with it. I realized that the data-sharing methods have not been implemented yet. They are great to share additional information per frame, for example camera intrinsics and extrinsics.

I also updated SpoutGL to the most recent version and prebuilt the binaries for x64 and x86 in release mode.

Looking forward to your feedback.

### CODE REVIEW

**Review by jlai — COMMENTED** [review]
Thanks for your PR contribution! Definitely should be useful for sharing additional data using Spout. I left a couple comments but otherwise it looks great.

**Comment by cansik** [comment]
@jlai Thanks for the suggestions!

**Comment by cansik** [comment]
I will fix the errors later today, I am currently on a Mac and do not have the tools for building it.

**Comment by cansik** [comment]
The build now works and the example runs as expected. I think that's all from my side.

**Comment by jlai** [comment]
Thanks for your contribution! And apologies for the typos in the suggestions, whoops. Released 0.0.3 to pypi

**Pull request merged**
